-include sdl3.dep
sdl3.lo: /home/thomas/projekte/phpnative/php-sdl3/sdl3.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/thomas/projekte/phpnative/php-sdl3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/thomas/projekte/phpnative/php-sdl3/sdl3.c -o sdl3.lo  -MMD -MF sdl3.dep -MT sdl3.lo
-include helper.dep
helper.lo: /home/thomas/projekte/phpnative/php-sdl3/helper.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/thomas/projekte/phpnative/php-sdl3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/thomas/projekte/phpnative/php-sdl3/helper.c -o helper.lo  -MMD -MF helper.dep -MT helper.lo
-include sdl3_image.dep
sdl3_image.lo: /home/thomas/projekte/phpnative/php-sdl3/sdl3_image.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/thomas/projekte/phpnative/php-sdl3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/thomas/projekte/phpnative/php-sdl3/sdl3_image.c -o sdl3_image.lo  -MMD -MF sdl3_image.dep -MT sdl3_image.lo
-include sdl3_ttf.dep
sdl3_ttf.lo: /home/thomas/projekte/phpnative/php-sdl3/sdl3_ttf.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/thomas/projekte/phpnative/php-sdl3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/thomas/projekte/phpnative/php-sdl3/sdl3_ttf.c -o sdl3_ttf.lo  -MMD -MF sdl3_ttf.dep -MT sdl3_ttf.lo
-include sdl3_events.dep
sdl3_events.lo: /home/thomas/projekte/phpnative/php-sdl3/sdl3_events.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/thomas/projekte/phpnative/php-sdl3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /home/thomas/projekte/phpnative/php-sdl3/sdl3_events.c -o sdl3_events.lo  -MMD -MF sdl3_events.dep -MT sdl3_events.lo
$(phplibdir)/sdl3.la: ./sdl3.la
	$(LIBTOOL) --tag=CC --mode=install cp ./sdl3.la $(phplibdir)

./sdl3.la: $(shared_objects_sdl3) $(SDL3_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sdl3) $(SDL3_SHARED_LIBADD)

